#!/bin/bash
#

getbg () {
	local OLDSTTY=$(stty -g)
	stty raw -echo min 0
	echo -en "\e]11;?\e\\" >/dev/tty
	read -t 0.1 -r -d '\' </dev/tty
	stty $OLDSTTY
	#_clevdump REPLY
	R1=`sed 's/^.*\;//;s/[^rgb:0-9a-f/]//g' <<<$REPLY`
	R2=`sed 's;.\+rgb:\(..\)../\(..\)../\(..\)...\+;\1 \2 \3;' <<<$REPLY`
	#_clevdump R1
	#_clevdump R2
	read R G B <<<$R2
}


#for I in 10 11 12 13 14 15  4\;{230..255}; do
#	C=`getrgb "$I"| sed 's;rgb:\(..\)../\(..\)../\(..\)..;\1 \2 \3;'`
#	#echo $C; od -a <<<$C
#	#read R G B <<<$(tr a-z A-Z <<<$C)
#	read R G B <<<$C
#	printf  "%6s: #%s%s%s\n" $I $R $G $B
#	bc <<-EOB
#		obase=16
#		ibase=16
#		mul=1.33
#		$R*mul
#		$G*mul
#		$B*mul
#	EOB
#done


