#!/bin/bash
#
# script that passes local resources to the remote machine and runs ssh
#

# store the whole file int one variable
CLE_64=$(base64 -w 0 clerc)

# it will be decoded on the other side
ssh -t $1 "echo $CLE_64|base64 -d >.clerc-$LOGNAME; export CLE_RMTUSER=$LOGNAME; exec bash --rcfile .clerc-$LOGNAME"

# that's all the magic here :-P

