#!/bin/sh
##
## ** CLE : Command Live Environment **
##
#* author:  Michael Arbet (marbet@redhat.com)
#* home:    https://github.com/micharbet/CLE
#* version: 2019-03-01 (Zodiac)
#* license: GNU GPL v2
#* Copyright (C) 2016-2019 by Michael Arbet

## ** WARNING! **
## This code is in super early development stage.
## Do not use, otherwise a puppy or kitten may die!
##

# Check if the shell is interactive session and CLE not yet started
# This is required for scp compatibility
[ -t 0 -a -z "$CLE_EXE" ] || return
# Now it really starts, warning: magic inside!

#:------------------------------------------------------------:#

# Debugging helpers							# dbg
dbg_echo () { [ $CLE_DEBUG ] && echo "$*" >/dev/tty; }			# dbg
dbg_var () (								# dbg
	eval "V=\$$1"							# dbg
	[ $CLE_DEBUG ] && printf "%-16s = %q\n" $1 "$V" >/dev/tty	# dbg
)									# dbg
#: ^^^ This was first bit of zsh/bash compatible code			# dbg
[ -f $HOME/CLEDEBUG ] && { CLE_DEBUG=1; }				# dbg
dbg_echo; dbg_echo CLE pid:$$ DEBUG ON;					# dbg

#:------------------------------------------------------------:#

# Startup sequence
#: First check how is this script executed
#:  - in case of a shell resource, this will be interactive session,
#:    prepare basic environment variables and do the shell specific tasks
#:  - in case of start as a command, open a shell (zsh or bash) and push this file
#:    as a resource
#: Then find out suitable shell and use it to run interactive shell session with
#: this file as init resource. The $CLE_RC variable must contain full path!
dbg_echo "startup case: '$ZSH_NAME$BASH:$0'"
case $ZSH_NAME$BASH:$0 in
*bash:*) # bash session resource
	dbg_echo sourcing to BASH
	CLE_RC=$BASH_SOURCE
	;;
*zsh:*zsh) # zsh session resource (started AS TEMPORARY .zshrc)
	dbg_echo sourcing to ZSH - from command
	# we know value of CLE_RC
	unset ZDOTDIR
	;;
*zsh:*/rc*) # started FROM .zshrc
	dbg_echo sourcing to ZSH - from .zshrc
	CLE_RC=$0
	;;
*:/*/rc*) # executed as a command from .cle directory
	#: code in this section must be strictly POSIX compatible with /bin/sh
	#: Now we're looking for suitable shell: zsh first, fallback to bash
	dbg_echo executing as script, looking for shell
	export CLE_RC=$(cd `dirname $0`;pwd;)/$(basename $0) # full path to this file
	ZS=`which zsh 2>/dev/null` # check zsh
	#: process command line options
	while [ $1 ]; do
		case $1 in
		-b*)	ZS= 	# force bash
			export CLE_ARG='-b'
			;;
		-z*)	export CLE_ARG='-z'
			;;
		-m)	CLE_MOTD=`uptime`
			export CLE_MOTD
			;;
		*)	echo "$0: unknown option '$1'"; exit 1;;
		esac
		shift
	done
	if [ $ZS ]; then
		dbg_echo found: $ZS
		#: prepare startup environment in zsh way
		export ZDOTDIR=/tmp/$USER
		mkdir -p $ZDOTDIR
		ln -sf $CLE_RC $ZDOTDIR/.zshrc
		exec zsh
	elif which bash >/dev/null 2>&1; then
		dbg_echo found: `which bash`
		exec bash --rcfile $0
	else
		echo "CLE needs bash or zsh. Giving up..."
		exit 1
	fi
	;;
*:*zclerc*)	# first run!
	#: code in this section must be strictly POSIX compatible with /bin/sh
	dbg_echo First run
	RD=$HOME/.zcle-$USER
	export CLE_1=$0
	mkdir -p $RD
	cp $0 $RD/rc1
	chmod 755 $RD/rc1
	exec $RD/rc1 "$@"
	;;
*)	echo something unknown;;
esac

#: Reaching this point means that the script is running as a resource
#: to the interactive session. Further code must be bash & zsh compatible!
dbg_echo ---------------
dbg_echo Resource starts
dbg_echo ---------------

#:------------------------------------------------------------:#
# Variables init

# CLE_RC can be relative path, make it full
CLE_RD=$(cd `dirname $CLE_RC`;pwd;)
CLE_RC=$CLE_RD/`basename $CLE_RC`
dbg_var CLE_RC
dbg_var CLE_RD

# who I am
#: determine username that will be inherited over the all
#: subsquent sessions initiated with lssh and su* wrappers
#: the regexp extracts username from following patterns:
#: - /any/folder/.cle-username/rcfile
#: - /any/folder/.config/cle-username/rcfile
#: important is the dot (hidden folder), word 'cle' with dash
_N=`sed -n 's;.*cle-\(.*\)/.*;\1;p' <<<$CLE_RC`
export CLE_USER=${CLE_USER:-${_N:-$(whoami)}}
dbg_var CLE_USER

# FQDN hack
#: `hostname -f` in some cases returns domain part only, without hostname!
#: Use the longer string. Also try `hostname' in case -f is't accepted (BSD) 
CLE_FHN=`hostname -f 2>/dev/null || hostname`
[ ${#CLE_FHN} -lt ${#HOST} ] && CLE_FHN=$HOST
CLE_IP=`cut -d' ' -f3 <<<$SSH_CONNECTION`

# where in the deep space CLE grows
CLE_SRC=https://raw.githubusercontent.com/micharbet/CLE/master
CLE_VER=`sed -n 's/^#\* version: //p' $CLE_RC`
CLE_VER="$CLE_VER debug"

# current shell and shell prefix
CLE_SH=`basename $BASH$ZSH_NAME`
CLE_SP='B'; [ $ZSH_NAME ] && CLE_SP=Z

# find writable folder
#: there can be real situation where a remote account is restricted and have no
#: home folder. In such case CLE can be started from /tmp. Also, after su*
#: wrapper the folder containing main resource file can be and usually will be
#: in different place than current home.
#: Simply to say, this sequence ensures customized configuration for every
#: account accessed with CLE.
[ -w $HOME ] || { HOME=/tmp/$USER; echo Temporary home: $HOME; }
CLE_D=$HOME/`sed 's:/.*/\(\..*\)/.*:\1:' <<<$CLE_RC`
mkdir -m 755 -p $CLE_D

# config, tweak, etc...
CLE_CF=$CLE_D/cf-$CLE_FHN
CLE_AL=$CLE_D/al
_N=`sed 's:.*/rc1*::' <<<$CLE_RC` # workstation name
CLE_WS=${_N/-/}
[ $CLE_USER != $USER -o -n "$CLE_WS" ] && CLE_LS=1
CLE_TW=$CLE_RD/tw$_N
CLE_ALW=$CLE_RD/al$_N
CLE_ENV=$CLE_RD/env$_N
CLE_TTY=`tty|tr -d '/dev'`

#:------------------------------------------------------------:#
# Internal functions

_clebnr () {
cat <<EOT

   ___| |     ____|  Command Live Environment activated
  |     |     __|    ...bit of life to the command line
  |     |     |      Learn more:$_CL cle help$_CN and$_CL cle doc$_CN
 \____|_____|_____|  Uncover the magic:$_CL less $CLE_RC$_CN

EOT
}

# boldprint
printb () { printf "$_CL$*$_CN\n";}

# simple question
ask () {
	local PR="$_CL$* (y/N) $_CN"
	[ $ZSH_NAME ] && read -ks "?$PR" || read -n 1 -s -p "$PR"
	echo ${REPLY:=n}
	[ "$REPLY" = "y" ]
}

# execute script and log its filename into CLE_EXE
# also ensure the script will be executed only once
_clexe () {
	[ -f "$1" ] || return 1
	[[ $CLE_EXE =~ :$1[:$] ]] && return
	CLE_EXE=$CLE_EXE:$1
	dbg_echo _clexe $1
	source $1
}
CLE_EXE=$CLE_RC

# Create color table
#: initialize $_C* variables with terminal compatible escape sequences
#: following are basic ones:
_cletable () {
	dbg_echo "_cletable updating color table"
	_C_=$TERM	#: save terminal type of this table
	_CN=`tput sgr0`
	_CL=`tput bold`
	_CU=`tput smul`;_Cu=`tput rmul`
	_CV=`tput rev`
	#: Note: dim and italic not available everywhere (e.g. RHEL)
	_CI=`tput sitm`;_Ci=`tput ritm`
	_CD=`tput dim`
	_Ck=$_CN$(tput setaf 0);_CK=$_Ck$_CL
	_Cr=$_CN$(tput setaf 1);_CR=$_Cr$_CL
	_Cg=$_CN$(tput setaf 2);_CG=$_Cg$_CL
	_Cy=$_CN$(tput setaf 3);_CY=$_Cy$_CL
	_Cb=$_CN$(tput setaf 4);_CB=$_Cb$_CL
	_Cm=$_CN$(tput setaf 5);_CM=$_Cm$_CL
	_Cc=$_CN$(tput setaf 6);_CC=$_Cc$_CL
	_Cw=$_CN$(tput setaf 7);_CW=$_Cw$_CL
	#: and... special color code for error highlight in prompt
	_Ce=`tput setab 1;tput setaf 7` # err highlight
}

# set prompt colors
_cleclr () {
	local C I CI
	case "$1" in
	red)    C=RrR;;
	green)  C=GgG;;
	yellow) C=YyY;;
	blue)   C=BbB;;
	cyan)   C=CcC;;
	magenta) C=MmM;;
	white|grey|gray) C=NwW;;
	tricolora) C=RBW;;
	marley) C=RYG;; # Bob Marley style :-) have a smoke and imagine...
	???|????)    C=$1;; # any 3/4 colors
	*)      # print help on colors
		printb "Unknown color '$1' Select predefined scheme:"
		declare -f _cleclr|sed -n 's/[ \t]*(*\(\<[a-z |]*\)).*/  \1/p'
		echo Alternatively create your own 3-letter combo using rgbcmykw/RGBCMYKW
		echo E.g. $_CL cle color rgB
		return 1
	esac
	# decode colors and prompt strings
	C=K${C}L
	for I in {0..4};do
		eval "CI=\$_C${C:$I:1}"
		[ -z "$CI" ] && printb "Wrong color code '${C:$I:1}' in $1" && CI=$_CN
		eval "_C$I=\$CI"
	done
}

# CLE prompt escapes
#: library of enhanced prompt escape codes introduced with ^ sign
#:  bash uses backslash while zsh percent sign for their prompt escapes
_clesc () (
	# bash/zsh specific sequences
	if [ $ZSH_NAME ]; then
		SHESC='-e "s/[\^]n/\$_PN/g"
		 -e "s/\^u/%n/g"
		 -e "s/\^w/%3~/g"
		 -e "s/\^t/%*/g"
		 -e "s/\^[$%#]/%#/g"
		'
	else
		SHESC='-e "s/\^n/\\\\n/g"
		 -e "s/\^u/\\\\u/g"
		 -e "s/\^w/\\\\w/g"
		 -e "s/\^t/\\\\A/g"
		 -e "s/\^[$%#]/\\\\\$/g"
		'
	fi
	EXTESC="
	 -e 's/\^i/\$CLE_IP/g'
	 -e 's/\^h/\$CLE_SHN/g'
	 -e 's/\^H/\$CLE_FHN/g'
	 -e 's/\^U/\$CLE_USER/g'
	 -e 's/\^g/\$(gitwb)/g'
	 -e 's/\^e/\\$_PE\$_CE\\$_Pe\[\$_EC\]\\$_PE\$_CN\$_C0\\$_Pe/g'
	 -e 's/\^c\(.\)/\\$_PE\\\$_C\1\\$_Pe/g'
	 -e 's/\^v\([[:alnum:]]*\)/\1=\$\1/g'
	 -e 's/\^\^/\^/g'
	"

	#: compose substitute command, remove unwanted characters
	SUBS=`tr -d '\n\t' <<<$SHESC$EXTESC`
	eval sed "$SUBS" <<<"$*"
)

# craft the prompt from defined strings
_cleps () {
	local I
	# override prompt strings with configured values
	#: use different variables for bash/zsh, eg. CLE_PB1 vs CLE_PZ1
	for I in 0 1 2 3 T; do
		eval "CLE_P$I=\${CLE_P$CLE_SP$I:-\$CLE_P$I}"
	done
	[ "$CLE_PT" ] && PS1="$_PE\${_CT}$(_clesc $CLE_PT)\${_Ct}$_Pe" || PS1=''
	PS1=$PS1`_clesc "^c0$CLE_P0 ^c1$CLE_P1 ^c2$CLE_P2 ^c3$CLE_P3 ^cN^c4"`
	PS2=`_clesc "^c3>>> ^cN^c4"`
}

# default prompt strings and colors
_cledefp () {
	CLE_P0='^e ^t'
	CLE_P1='^u'
	CLE_P2='^h'
	CLE_P3='^w ^$'
	CLE_PT='$CLE_SH: ^u@^H'
	case "$USER-$CLE_WS" in
	root-)	_DEFC=red;;	#: root@workstation
	*-)	_DEFC=marley;;	#: user's basic color scheme
	root-*)	_DEFC=RbB;;	#: root@remote
	*-*)	_DEFC=blue;;	#: user@remote
	esac
}

# save configuration
_clesave () (
	date +"# CLE/$CLE_VER %Y-%m-%d %H:%M:%S"
	vars "CLE_CLR|CLE_PB.|CLE_PZ."
) >$CLE_CF


# prompt callback functions
#: As precmd function is executed *every* time you push enter key its code
#: should be as simple as possible. In best case all commands here should be
#: bash internals. Those don't invoke new processes and as such they are much
#: easier to system resources.
CLE_HIST=$HOME/.clehistory
precmd () {
	_EC=$? # save return code
	local IFS S DT C
	unset IFS
	[ $BASH ] && C=`HISTTIMEFORMAT=";$CLE_HTF;" history 1` || C=`fc -lt ";$CLE_HTF;" -1`
	C=${C#*;}	#: strip sequence number
	DT=${C/;*}	#: extract date
	C=${C/$DT;}	#: extract command
	C="${C#"${C%%[![:space:]]*}"}" #: remove leading spaces (needed in zsh)
	#: ^^^ found here: https://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable
	if [[ $C =~ ^# ]]; then
		_clerh  "$DT" '' \# note "$C" #: record notes to rich history
	elif [ $_SST ]; then
		#: this code will be executed only after an valid command
		S=$((SECONDS-_SST))
		_clerh "$DT" $S $_EC $PWD "$C"
		[ $_EC = 0 ] && _CE="" || _CE="$_Ce" #: highlight error code
		_SST=
	else
		_CE=''; _EC=0 #: reset error code
	fi
	[ $BASH ] && trap _clepreex DEBUG
}

# run this function before the issued command
preexec () {
	_SST=$SECONDS #: start timer
	echo -n $_CN  #: reset tty colors
}

# Bash hack
#: Zsh supports preexec function naturaly. This is bash's workaround.
_clepreex () {
	[ "$BASH_COMMAND" = $PROMPT_COMMAND ] && return
	trap "" DEBUG
	preexec "$BASH_COMMAND"
}

# rich history record
_clerh () {
	local DT EXC
	#: ignore marked commands
	[ $_NORH ] && unset _NORH && return
	# exclude regexp
	#: `vv` generates its record
	#: folder is visible so no need to record `cd`
	EXC="^vv\ |^cd\ |^cd$|^-$|^xx$|^aa$|^lscreen"
	#: check timestamp and create if missing
	if [ $# -lt 5 ]; then
		DT=`date "+$CLE_HTF"`
	else
		DT=$1
		shift
	fi
	[[ $4 =~ $EXC ]] && return
	echo -E "$DT;$CLE_USER-$CLE_SP$$;$1;$2;$3;$4" >>$CLE_HIST
}


# Use alias built-ins for startup
#: alias & unalias must be available in their natural form now
#: and will be redefined at the end of resource
unset -f alias unalias 2>/dev/null

#: Run profile files
#: Things in /etc/profile.d can override some settings.
#: E.g. there might be vte.sh defining own PROMPT_COMMAND and this completely
#: breaks rich history.
_clexe /etc/profile
_clexe $HOME/.${CLE_SH}rc

# print MOTD + more
if [ "$CLE_MOTD" ]; then
	[ -f /etc/motd ] && cat /etc/motd
	printf "\n$CLE_MOTD"
	printb "\n CLE/$CLE_SH $CLE_VER\n"
	unset CLE_MOTD
fi

# Aliasing
# first load aliases inherited from CLE workstation
#: On workstation: load aliases later
#: On live sessions: read inherited aliases first, allow redefining locally
[ $CLE_AL != $CLE_ALW ] && _clexe $CLE_ALW

# colorize LS
case $OSTYPE in
linux*)		alias ls='ls --color=auto';;
darwin*)	export CLICOLOR=1; export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd;;
FreeBSD*)       alias ls='ls -G "$@"';;
*)		alias ls='ls -F';; # at least some file type indication
esac

# colorized GREP except on busybox
#: busybox identified by symlinked 'grep' file
if [ -L `command which grep` ];then
	#: Fedora defines this mess :(
	unalias grep egrep fgrep xzgrep xzegrep xzfgrep zgrep zegrep zfgrep
else
	alias grep='grep --color=auto'
fi

# Remove alias 'which' if there is no version supporting extended options
#: This weird construction ensures that the 'which' will work even in case
#: there's an alias containing extended options inherited from such system
#: to the one with simpler 'which' E.g. Fedora supports option --read-alias
#: but Debian, and BSD do not have this version of 'which' command.
{ alias|command which -i which || unalias which; } >/dev/null 2>&1

## ** cd command enhancements **
## `.. ...`     - up one or two levels
## `-`  (dash)  - cd to recent dir
- () { cd -;}
.. () { cd ..;}
... () { cd ../..;}
## `xx` & `cx`   - bookmark $PWD & use later
xx () { _XX=$PWD;_clerh '' '*' $PWD ''; echo path bookmark: $_XX; }
cx () { cd $_XX; }

##
## ** Alias management **
aa () {
	local AED=$CLE_AL.ed
	local Z=${ZSH_NAME:+-L}
	case "$1" in
	"")	## `aa`         - show aliases
		#: also make the output nicer and more easy to read
		builtin alias $Z|sed "s/^alias \([^=]*\)=\(.*\)/$_CL\1$_CN\t\2/";;
	-s)	## `aa -s`      - save aliases
		builtin alias $Z >$CLE_AL;;
	-e)	## `aa -e`      - edit aliases
		builtin alias $Z >$AED
		vi $AED
		[ $ZSH_NAME ] && builtin unalias -m '*' || builtin unalias -a
		. $AED;;
	*=*)	## `aa a='b'`   - create new alias and save
		builtin alias "$*"
		aa -s;;
	*)	builtin alias "$*";;
	esac
}

##
## ** History tools **
## REWORKING RICH HISTORY FROM SCRATCH
## `h`               - shell 'history' wrapper
CLE_HTF=
h () {
	([ $BASH ] && HISTTIMEFORMAT=";$CLE_HTF;" history "$@" || fc -lt ";$CLE_HTF;" "$@")|( IFS=';'; while read -r N DT C;do
		echo -E "$_CB$N$_Cb $DT $_CN$_CL$C$_CN"
	done;) 
	_NORH=1
}

## `hh [opt] [srch]` - rich history viewer
hh () {
	#: Compose read filter
	case "$1" in
	'')	SEARCH="tail -100 $CLE_HIST"
		;;
	*[!0-9]*)
		SEARCH="grep '$1' $CLE_HIST"
		;;
	*)	SEARCH="tail -$1 $CLE_HIST"
		;;
	esac

	OUTF=_clehhout
	# commands only
	#OUTF="sed -n 's/^[^;]*;[^;]*;[^;]*;[0-9]*;[^;]*;\(.*\)/\1/p'"
	# directories
	#OUTF="sed -n 's/^[^;]*;[^;]*;[^;]*;[0-9]*;\([^;]*\);.*/\1/p'"

	#: execute filters
	eval "$SEARCH | $OUTF"
	_NORH=1
}

# rich history colorful output filter
_clehhout () (
	IFS=';'
	while read -r DT SID SEC EC D C; do
		case $EC in
		 0) CE=$_Cg; CC=$_CN;;
		 @) CE=$_Cg; CC=$_Cg;;
		 '#'|$|'*') CE=$_CY; CC=$_Cy;;
		 *) CE=$_Cr; CC=$_CN;;
		esac
		printf "$_CB%s $_Cb%s $_CB%4s $CE%-3s $CC%s  $_CL" "$DT" "$SID" "$SEC" "$EC" "$D"
		cat <<<$C #: this cannot be part of printf above to keep possible backslashes
	done
)

## `vv VARNAME`      - show variable details and record them into rich history
vv () (
	[ $1 ] || return
	V=`typeset -p $1` || return
	echo -E $V
	_clerh '' \$ var "`tr '\n' ' ' <<<$V`"
)


# zsh hack to accept notes on cmdline
[ $ZSH_NAME ] && '#' () { true; }

##
## ** Not-just-internal tools **
## `vars 'regexp'`   - dump variables in reusable way, bash/zsh compatible
#: it was difficult to create this shot function and make it working
#: in both zsh and bash because:
#:  - in bash 'set' displays also functions - this is why there's 
#:    first awk command: "/.* \(\)/ {exit}"
#:  - zsh dereferences variable differently
#:  - zsh on debian doesn't quote escape strings and 'mawk' stops
#:    processing on special characters, gawk is required!
#: This function might be useful also as command thus named without underscore
vars () (
	set 2>/dev/null | awk -F= "/.* \(\)/{exit} /^($1)=/ {print \$1}" | while read N
	do
		eval "V=\$$N"
		printf %s=%q\\n $N "$V"
	done
)

## `gitwb`            - show current working branch name
gitwb () (
	# search all parent directories
	while [ $PWD != / ]; do
		[ -d .git ] && { git symbolic-ref --short HEAD; return; }
	cd ..
	done
	return 1  # not in git repository
	)


## `mdfilter`        - markdown acsii highlighter
#: Highly sophisticated filter :-D
#: Just replaces special strings in markdown files and augments the output
#: with escape codes to highlight.
#: Not perfect, but it helps and is simple, isn't it?
mdfilter () {
	sed -e "s/^###\(.*\)/$_CL\1$_CN/"\
	 -e "s/^##\( *\)\(.*\)/\1$_CU$_CL\2$_CN/"\
	 -e "s/^#\( *\)\(.*\)/\1$_CL$_CV \2 $_CN/"\
	 -e "s/\*\*\(.*\)\*\*/$_CL\1$_CN/"\
	 -e "s/\<_\(.*\)_\>/$_CU\1$_Cu/g"\
	 -e "s/\`\`\`/$_CD~~~~~~~~~~~~~~~~~$_CN/"\
	 -e "s/\`\([^\`]*\)\`/$_Cg\1$_CN/g"
}


#:------------------------------------------------------------:#
##
## ** Live session wrappers **

# environment packer
#: grab *active* resource file, tweak file, pack it to tarball and store
#: into variable C64 as base64 encoded string.
#: Argument ($1) may contain additional suffix to filenames
#: Second outcome of _clepak is value in $RC - relative path to the resource
#: file that should be run on remote system (it may contain the suffix)
#: Note: configuration is not packed in order to ensure unique cf on all
#:  remote accounts.
#: Note 2: _clepak is defined with curly brackets {} to pass variables RC and C64
#:  On the other side lssh is defined with () ensuring execution in its own context
#:  where all new variables are local only to lssh (and _clepak)
#: Note 3: _clepak is fuction even if it is used only once and could be
#:  included directly into lssh. However, this allows to create any other
#:  remote access wrapper
_clepak () {
	#: anything up to first dotted folder is home for .cle folder
	vars "CLE_P..|_C.|$CLE_VARS" >$CLE_ENV
	cd `sed 's:\(/.*\)/\..*:\1:' <<<$CLE_RC`
	RC=${CLE_RC/$PWD\//}
	TW=${CLE_TW/$PWD\//}
	AL=${CLE_ALW/$PWD\//}
	EN=${CLE_ENV/$PWD\//}
	if [ $1 ];then
		#: change names and copy files when adding suffix
		#: this happens when doing lssh (from CLE ws)
		RC=$RC$1; TW=$TW$1; AL=$AL$1; EN=$EN$1
		cp $CLE_RC $RC
		cp $CLE_TW $TW 2>/dev/null
		cp $CLE_AL $AL 2>/dev/null
		cp $CLE_ENV $EN
	fi
	RCS="$RC $TW $AL $EN"
	dbg_var PWD
	dbg_var RCS
	#:  I've never owned this computer, I had Atari 800XL :)
	C64=`eval tar chzf - $RCS 2>/dev/null | base64 | tr -d '\n\r '`
	#: 'eval' required due to zsh.
}

## `lssh [usr@]host`   - access remote system and take CLE along
lssh () (
	[ "$1" ] || { cle help lssh;return 1;}
	#: on CLE workstation, suffix to resource filename is added
	#: this 1. prevents overwriting on destination accounts
	#:  and 2. provides information about source of the session
	S= #: resource suffix is empty on remote sessions...
	[ $CLE_WS ] || S=-$CLE_FHN #: adding suffix when running on WS
	_clepak $S
	[ $CLE_DEBUG ] && echo -n $C64 |base64 -d|tar tzvf -
	command ssh -t $* "
		[ -w \$HOME ] && _H=\$HOME || _H=/tmp/\$USER
		[ $OSTYPE = darwin ] && _D=D || _D=d
		mkdir -m 755 -p \$_H; cd \$_H
		echo -n $C64|base64 -\$_D |tar xzf -;
		exec $RC -m $CLE_ARG"
)

#: Following are su* wrappers of different kinds including kerberos
#: version 'ksu'. They are basically simple, you see. Environment is not
#: packed and transferred when using them. Instead the original files from
#: user's home folder are used.
## `lsudo [user]`      - sudo wrapper; root is the default account
lsudo () (
	[ $CLE_LS ] || vars "CLE_P..|_C.|$CLE_VARS" >$CLE_ENV
        sudo -i -u ${1:-root} $CLE_RC $CLE_ARG
)

## `lsu [user]`        - su wrapper
#: known issue - on debian systems controlling terminal is detached in case 
#: a command ($CLE_RC) is specified, use 'lsudo' instead
lsu () (
	[ $CLE_LS ] || vars "CLE_P..|_C.|$CLE_VARS" >$CLE_ENV
        S=
        [[ $OSTYPE =~ [Ll]inux ]] && S="-s /bin/sh"
        eval su $S -l ${1:-root} $CLE_RC
)

## `lksu [user]`       - ksu wrapper
#: Kerberized version of 'su'
lksu () (
	[ $CLE_LS ] || vars "CLE_P..|_C.|$CLE_VARS" >$CLE_ENV
        ksu ${1:-root} -a -c $CLE_RC
)

## `lscreen [name]`    - gnu screen wrapper, join your recent session or start new
## `lscreen -j [name]` - join other screen sessions, ev. search by name
#: GNU screen wrapper is here 1) because of there was no way to tell screen
#: program to start CLE on more than first window and, 2) to allow easily
#: join detached own session and/or join cooperative session with more
#: participants.
lscreen () (
	#: get name of the screen to search and join
	#: base of session name is $CLE_USER and this can be extended
	NM=$CLE_USER${1:+-$1}
	[ "$1" = -j ] && NM=${2:-.}
	#: list all screens with that name and find how many of them are there
	SCRS=`screen -ls|sed -n "/$NM/s/^[ \t]*\([0-9]*\.[^ \t]*\)[ \t]*.*/\1/p"`
	NS=`wc -w <<<$SCRS`
	if [ $NS = 0 ]; then
		[ "$1" = -j ] && echo "No screen to join" && return 1
		#: No session with given name found, prepare to start new session
		SCF=$CLE_D/screenrc
		SN=$CLE_TTY-CLE.$NM
		_clerh '' @ $CLE_TTY "screen -S $SN"
		_clescrc >$SCF
		screen -c $SCF -S $SN $CLE_RC
	else
		#: is there only one such session or more?
		if [ $NS = 1 ]; then SN=$SCRS
		else
			#: we found more screens with simiilar names, choose one!
			printb "${_CU}Current '$NM' sessions:"
			PS3="$_CL choose # to join: $_CN"
			select SN in $SCRS;do
				[ $SN ] && break
			done
		fi
		_clerh '' @ $CLE_TTY "screen -x $SN"
		#: send message to other screen, then join the session
		screen -S $SN -X echo "$CLE_USER joining"
		screen -x $SN
	fi
)

# screenrc generator
#: This generates nice configuration file with cool features:
#:  - always visible status line with list of windows, hostname and clock
#:  - feature to quickly switch using Ctrl+Left/Right Arrows
#:  - reads good old $HOME/.screenrc
#: Own screenrc file is necessary because otherwise it wouldn't start CLE in
#: subsequent windows created with 'C-a C-c' (note the bind commands, above
#: mentioned features are cool but this part is the important one)
_clescrc () {
cat <<-EOS
	source $HOME/.screenrc
	altscreen on
	autodetach on
	# enables shift-PgUp/PgDn
	termcapinfo xterm* ti@:te@
	# change window with ctrl-left/right
	bindkey "^[[1;5D" prev
	bindkey "^[[1;5C" next
	defscrollback 9000
	hardstatus alwayslastline
	hardstatus string '%{= Kk} %-w%{Wk}%n %t%{-}%+w %-=%{+b Y}$CLE_SHN%{G} %c'
	bind c screen $CLE_RC
	bind ^c screen $CLE_RC
EOS
}


#:------------------------------------------------------------:#
# config, tweaks, env

_clexe $HOME/.cle-local
_clexe $CLE_AL
_clexe $CLE_TW
[ $ZSH_NAME ] && setopt +o NOMATCH #: stop annoying zsh error when '*' doesn't match any file
for M in $CLE_RD/mod-*; do
	_clexe $M
done

#: Enhnace PATH by user's own bin folder
[[ -d $HOME/bin && ! $PATH =~ $HOME/bin ]] && PATH=$PATH:$HOME/bin

# shorten hostname
#: by default remove domain, leave subdomains
#: eventually apply CLE_SRE as sed regexp for custom shortening
CLE_SHN=`eval sed "${CLE_SRE:-'s:\.[^.]*\.[^.]*$::'}" <<<$CLE_FHN`

# create the prompt in several steps
# 1. default prompt strings
_cledefp
if [ $CLE_LS ]; then
	# 2. override with inherited strings
	_clexe $CLE_ENV
	for I in 0 1 2 3 T; do
		#: Copy and discard inherited values.
		#: This ensures the inherited values will not be saved into
		#: local configuration unless redefined in the session
		eval "CLE_P$I=\${CLE_P$CLE_SP$I:-\$CLE_P$I}"
		unset CLE_PB$I CLE_PZ$I
	done
	[ $TERM != $_C_ ] && _cletable #: changed terminal type, reinitilaize color table
else
	# initialize color table on workstation
	_cletable
fi

# 3. get values from config file
_clexe $CLE_CF

# 4. termnal specific
#: $_CT and $_Ct are codes to create window title
#: also in screen the title should be short and obviously no title on text console
case $TERM in
linux)	 CLE_PT='';;	# no tits on console
screen*) CLE_PT='^u'
	_CT=$'\ek'; _Ct=$'\e\\';;
*)	_CT=$'\e]0;'; _Ct=$'\007';;
esac

# 5. shell specific
#: $_PE nad $_Pe keep strings to enclose ansi control charaters in prompt
if [ $BASH ]; then
	shopt -s checkwinsize
	_PE='\['; _Pe='\]'
else
	setopt PROMPT_SUBST SH_WORD_SPLIT
	_PE='%{'; _Pe='%}'
	_PN=$'\n' # zsh doesn't know '\n' as escape sequence! WTF?
fi

# 6. craft the prompt string
_cleps
_cleclr ${CLE_CLR:-$_DEFC}
unset _DEFC

PROMPT_COMMAND=precmd
PROMPT_DIRTRIM=3

HISTCONTROL=ignoredups
HISTFILE=$CLE_D/history-$CLE_SH
CLE_HTF='%Y-%m-%d %T'

# completions
#: Command 'cle' completion
#: as an addition, prompt strings are filled for convenience :)
if [ $BASH ]; then
	_clecomp () {
		#: list of subcommands, this might be reworked to have possibility of expansion
		#: with modules (TODO)
		#: 'cle deploy' is hidden intentionaly as user should do it only on when really needed
		local A=(color p0 p1 p2 p3 time title mod env update reset reload doc help)
		local C
		COMPREPLY=()
		case $3 in
		p0) COMPREPLY="'$CLE_P0'";;
		p1) COMPREPLY="'$CLE_P1'";;
		p2) COMPREPLY="'$CLE_P2'";;
		p3) COMPREPLY="'$CLE_P3'";;
		esac
		[ "$3" != "$1" ] && return
		for C in ${A[@]}; do
			[[ $C =~ ^$2 ]] && COMPREPLY+=($C)
		done
		}
	complete -F _clecomp cle

	#: lssh completion
	#: there are two possibilities of ssh completion _known_hosts is more common...
	declare -F _known_hosts >/dev/null && complete -F _known_hosts lssh
	#: while _ssh is better
	#: The path is valid at least on fedora and debian with installed bash-completion package
	_C=/usr/share/bash-completion/completions/ssh
	if [ -f $_C ]; then
		. $_C
		complete -F _ssh lssh
	fi
else
	# ZSH completion here
	echo NO ZSH COMPLETION YET
fi

# redefine alias builtins
#: those definitions must be here, only after config and tweaks not to mess
#: with builtin shell functions during startup. This also speeds up the thing
alias () {
	if [ -n "$1" ]; then
		aa "$@"
	else
		builtin alias
	fi
}

unalias () {
	[ "$1" = -a ] && cp $CLE_AL $CLE_AL.bk  # BASH only!
	builtin unalias "$@"
	aa -s
}

# check manual start
[ $CLE_1 ] && cat <<EOT
 It seems you started CLE running '$CLE_1' from command line
 Since this is the first run, consider setup in your profile.
 Run following command to hook CLE into your $HOME/.${CLE_SH}rc:
$_CL    cle deploy
EOT

[ -r . ] || cd #: go home if this is unreadable directory

# record this startup into rich history
_clerh '' @ "${STY:-${CLE_WS:-WS}}->$CLE_TTY($TERM)" "$CLE_SH $CLE_RC  $CLE_VER"

##
## ** CLE command & control **
cle () {
	local C I P
	case $1 in
	color)  ## `cle color COLOR`       - set prompt color
		[ $2 ]  && _cleclr $2 && CLE_CLR=$2 && _clesave;;
	p?)	## `cle p0-p3 [str]`       - show/define prompt parts
		I=${1:1:1}
		if [ "$2" ]; then
			shift
			P=CLE_P$CLE_SP$I   #: save to shell-corresponding variable
			eval "$P='$*'"
			_cleps;_clesave
		else
			P=CLE_P$I
			eval "echo $P=\'\$$P\'"
		fi;;
	title)	## `cle title off|string`  - turn off window title or set the string
		[ "$2" = off ] && CLE_PT='' || CLE_PT=${2:-'$CLE_SH: ^u@^H'}
		_cleps;;
	deploy) ## `cle deploy`            - hook CLE into user's profile
		cp $CLE_RC $CLE_D/rc
		CLE_RC=$CLE_D/rc
		unset CLE_1
		I='# Command Live Environment'
		SHRC=$HOME/.${CLE_SH}rc
		grep -A1 "$I" $SHRC && printb CLE is already hooked in $SHRC && return 1
		ask "Do you want to add CLE to $SHRC?" || return
		echo -e "\n$I\n[ -f $CLE_RC ] && . $CLE_RC\n" | tee -a $SHRC
		cle reload;;
	update) ## `cle update`            - install fresh version of CLE
		NC=$CLE_D/rc.new
		curl -k $CLE_SRC/zclerc >$NC      # always update from master branch
		C=`sed -n 's/^#\* version: //p' $NC`
		[ "$C" ] || { echo "Download error"; return 1; }
		echo current: $CLE_VER
		echo "new:     $C"
		MM=`diff $CLE_RC $NC` && { echo No difference; return 1;}
		ask Do you want to see diff? && cat <<<"$MM"
		ask Do you want to install new version? || return
		BRC=$CLE_D/rc.bk
		cp $CLE_RC $BRC
		chmod 755 $NC
		mv -f $NC $CLE_RC
		cle reload
		printb New CLE activated, backup saved here: $BRC;;
	reload) ## `cle reload [bash|zsh]` - reload CLE
		SH=${2:-$CLE_SH}
		exec $CLE_RC -$SH
		case $SH in
		bash)	exec bash --rcfile $CLE_RC;;
		zsh)	exec zsh -c $CLE_RC;;
		*)	echo no such shell: $2
			return 1;;
		esac;;
	env)	## `cle env`  -            - inspect variables
		set|awk -F= "/.* \(\)/{exit}  /^CLE.*=/ {printf \"$_CL%-12s$_CN%s\n\",\$1,\$2}";;
	cf)	## `cle cf [ed|reset]`     - view/edit/reset/revert configuration
		case "$2" in
		ed)	vi $CLE_CF  && . $CLE_RC;;
		reset)	mv $CLE_CF $CLE_CF-bk;;
		revert)	cp $CLE_CF-bk $CLE_CF;;
		"")
			if [ -f $CLE_CF ]; then
				printb $_CU$CLE_CF:
				cat $CLE_CF
			else
				echo Default/Inherited configuration
			fi
			return;;
		esac
		cle reload;;
	ls)	printb CLE_D: $CLE_D; ls -l $CLE_D; printb CLE_RD: $CLE_RD; ls -l $CLE_RD;;	# dbg
	exe)	echo $CLE_EXE|tr : \\n;;							# dbg
	debug)	[ "$2" = off ] && CLE_DEBUG='' || CLE_DEBUG=${2:-on}				# dbg
		dbg_var CLE_DEBUG ;;								# dbg
	help|-h|--help) ## `cle help [fnc]`  -     - show help
		# double hash denotes help content
		C=`ls "$CLE_D/cle-*" 2>/dev/null`
		awk -F# "/[\t ]## *\`*$2|^## *\`*$2/ { print \$3 }" ${CLE_EXE//:/ } $C | mdfilter | less -erFX;;
	"")
		_clebnr
		sed -n 's/^#\*\(.*\)/\1/p' $CLE_RC
		;;
	*)
		echo unimplemented: cle $C;
		echo check cle help;
		return 1
		;;
	esac
}

##
#: final cleanup
unset _N

# that's all, folks...

